name: ğŸ—ï¸ Auto PR Creation (Infra)

on:
  push:
    branches:
      - 'TEM-*'

jobs:
  create-pr:
    uses: T-ESP-ASSTAGJ/infra/.github/workflows/reusable_pr-creation.yml@main
    with:
      repository_name: "infra"
      base_branch: "staging"
    secrets:
      AUTO_DEPLOY_TOKEN: ${{ secrets.AUTO_DEPLOY_TOKEN }}
